# Generated by Django 4.1 on 2024-06-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ucret",
            fields=[
                ("ucretid", models.AutoField(primary_key=True, serialize=False)),
                ("ucret", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
