# Generated by Django 4.1 on 2024-06-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tekne", "0002_rezerve_tekne_tur"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rezerve",
            old_name="tekne",
            new_name="teknename",
        ),
        migrations.RenameField(
            model_name="rezerve",
            old_name="tur",
            new_name="turname",
        ),
    ]
