# Generated by Django 4.1 on 2024-06-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekne', '0003_rename_tekne_rezerve_teknename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerve',
            name='tarih',
            field=models.DateField(blank=True, null=True),
        ),
    ]
