# Generated by Django 4.1 on 2024-06-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekne', '0004_alter_rezerve_tarih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerve',
            name='kapora',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rezerve',
            name='telno',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
