# Generated by Django 4.1 on 2024-06-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekne', '0005_alter_rezerve_kapora_alter_rezerve_telno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerve',
            name='kapora',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rezerve',
            name='telno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
