# Generated by Django 4.1 on 2024-06-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tekne', '0006_alter_rezerve_kapora_alter_rezerve_telno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rezerve',
            old_name='rezerveid',
            new_name='id',
        ),
    ]
