# Generated by Django 4.1 on 2024-06-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekne', '0007_rename_rezerveid_rezerve_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerve',
            name='tamucret',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
